### ISSUE TITLE
keyLogger not working continuously

### ISSUE THREAD

**Issue by Aravindhan95** [muneebwanee/Dash#13]
Key logger working fine. But most of the time not working and not updating into firebase.

**Comment by TeamDarkAnon** [comment]
bro can you share any tutorial of it  ?

**Comment by rifas9037** [comment]
> bro can you share any tutorial of it ?

I know

**Comment by diliplilaramani** [comment]
yes keylogger stopped working after 24 hours. Any solution?

**Comment by lampion955** [comment]
which tutorial bro

Pada tanggal Min, 4 Sep 2022 21.52, rifas9037 ***@***.***>
menulis:
