### ISSUE TITLE
build.gradle and other mistakes

### ISSUE THREAD

**Issue by fortunatodan** [muneebwanee/Dash#15]
First I want to thank the creator of the project, it's amazing, and then I also want to say that I'm jealous that he managed to create it in Android Studio (laughs).

I've been trying to create the project in Android Studio for about 4 days, I've researched a lot, and I can't do it at all!

After importing the project here from GitHub to Android Studio, it gives me an ASCII error (I already checked all the folders in my project and none of them have an accent or special characters), after researching a little more I saw that it is the Gradle version. Who managed to compile used which version of:
"Android Gradle Plugin Version" and "Gradle Version" in project?

"apply plugin: 'kotlin-kapt'" can this part be removed from the code or left?

(I'm sorry for anything in the message, I'm Brazilian and I'm using Google translator)

![image](https://github.com/muneebwanee/Dash/assets/82962685/9216bc34-48ef-498d-9b14-2ac152f71de4)

**Comment by brunolacerda** [comment]
estou com o mesmo problema
