### ISSUE TITLE
The mapper returned a null value

### ISSUE THREAD

**Issue by fortunatodan** [muneebwanee/Dash#16]
I did the whole installation process correctly, but when opening the app it issues the warning "the mapper returned a null value", and the "child" does not appear in the list. (I put my Google Maps API) ... In the output of Logcat informs:
"Error opening kernel wakelock stats for: wakeup34: Permission denied"

I'm sorry for "my" English, I'm using Google translator, I'm Brazilian.

![image](https://github.com/muneebwanee/Dash/assets/82962685/92381cef-32e9-4b21-921c-13c100a48939)

**Comment by panam91** [comment]
@fortunatodan  can u help me to run it ?
