### ISSUE TITLE
We are expecting a reply

### ISSUE THREAD

**Issue by xy0893** [muneebwanee/Dash#2]
Good afternoon, sir. Is there a tutorial for this software? Can windows be used?

**Comment by muneebwanee** [comment]
Hey mate, 
You can use [android studio](https://developer.android.com/studio) to build this project. And for tutorial you can refer to - [Build this project](https://github.com/muneebwanee/Dash#build-this-project)

**Comment by muneebwanee** [comment]
For video tutorial you have to wait till Sep-2021
Thanks
