### ISSUE TITLE
error with com.github.romancha:MaterialPlayPauseViewButton:1.0.1. library

### ISSUE THREAD

**Issue by Tushar143s** [muneebwanee/Dash#3]
Unable to resolve dependency for ':app@debugUnitTest/compileClasspath': Could not resolve com.github.romancha:MaterialPlayPauseViewButton:1.0.1.
Show Details
Affected Modules: app

Unable to resolve dependency for ':app@debugAndroidTest/compileClasspath': Could not resolve com.github.romancha:MaterialPlayPauseViewButton:1.0.1.
Show Details
Affected Modules: app

Unable to resolve dependency for ':app@debug/compileClasspath': Could not resolve com.github.romancha:MaterialPlayPauseViewButton:1.0.1.
Show Details
Affected Modules: app

**Comment by Tushar143s** [comment]
We have alternative library for the same https://github.com/zhanghai/MaterialPlayPauseDrawable can just modify your code for the same.

**Comment by muneebwanee** [comment]
Thanks for letting me know. You can make a pull request for the same.

**Comment by muneebwanee** [comment]
Change com.github.romancha:MaterialPlayPauseViewButton:1.0.1 to me.zhanghai.android.materialplaypausedrawable:library:1.0.0

@ app/build.gradle & app/app.iml
