### ISSUE TITLE
Unresolved reference: dash

### ISSUE THREAD

**Issue by sayeedhossain** [muneebwanee/Dash#8]
Check out the attached screenshot for better understanding. Help me to fix this issue. It's very urgent. Please help anyone. 

![Screenshot from 2022-03-05 00-08-25](https://user-images.githubusercontent.com/46787924/156818556-4cf85001-3ec3-44b5-9d4c-2b7ee105919f.png)
![Screenshot from 2022-03-05 00-08-46](https://user-images.githubusercontent.com/46787924/156818580-f0c11e87-3406-4647-998a-380fa2d7dfbb.png)
![Screenshot from 2022-03-05 00-09-13](https://user-images.githubusercontent.com/46787924/156818584-f49b0104-fd86-449a-84c4-23ebdb499660.png)

**Comment by muneebwanee** [comment]
Change "dash to Dash"

**Comment by muneebwanee** [comment]
Updated Dash

Now import Dash from github.com/muneebwanee/Dash

**Comment by muneebwanee** [comment]
Updated Dash

Now import Dash from github.com/muneebwanee/Dash
