### ISSUE TITLE
Social or phishing option is not working. 

### ISSUE THREAD

**Issue by blackholeteam7287** [muneebwanee/Dash#9]
When I click on social from the parent phone then nothing happens on the child phone.And also the phishing page is not open on the child phone. 
In **_build.gradle_** , I already add the following line of code. 
 ```
ext {
        PACKAGE_CHECK_SOCIAL = "\"PHISHING-SOCIAL_NETWORK\""
    }
```
But nothing happens on the child phone and I don't get any credential. 

![275011588_647507489858373_2375430055649302615_n](https://user-images.githubusercontent.com/101231638/157358774-e475d23d-ef26-4925-b7c8-da1ce3a8074d.jpg)

**Comment by preston119** [comment]
May I ask you how did you get through Select Child page right before you login as parent? My parent screen shows no child although it is successfully logged in in child's phone. I checked that the authentication works in firebase
